# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'GUIs/admission_menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_admission(object):
    def setupUi(self, admission):
        admission.setObjectName("admission")
        admission.resize(988, 578)
        admission.setStyleSheet("background-color: rgb(8, 8, 8);\n"
"font-family: Times New Roman;\n"
"")
        self.frame = QtWidgets.QFrame(admission)
        self.frame.setGeometry(QtCore.QRect(28, 180, 341, 331))
        self.frame.setStyleSheet("QFrame{\n"
"    border: 2px solid white;\n"
"\n"
"}")
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame.setObjectName("frame")
        self.label = QtWidgets.QLabel(self.frame)
        self.label.setGeometry(QtCore.QRect(20, 20, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label.setFont(font)
        self.label.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.frame)
        self.label_2.setGeometry(QtCore.QRect(20, 140, 101, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.frame)
        self.label_3.setGeometry(QtCore.QRect(20, 100, 121, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.frame)
        self.label_4.setGeometry(QtCore.QRect(20, 60, 91, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.frame)
        self.label_5.setGeometry(QtCore.QRect(20, 190, 81, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_5.setObjectName("label_5")
        self.frame_2 = QtWidgets.QFrame(self.frame)
        self.frame_2.setGeometry(QtCore.QRect(140, 140, 181, 41))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.frame_2.setFont(font)
        self.frame_2.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.maleradio = QtWidgets.QRadioButton(self.frame_2)
        self.maleradio.setGeometry(QtCore.QRect(10, 10, 100, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.maleradio.setFont(font)
        self.maleradio.setStyleSheet("color: white;\n"
"BACKGROUND: ")
        self.maleradio.setObjectName("maleradio")
        self.femaleradio = QtWidgets.QRadioButton(self.frame_2)
        self.femaleradio.setGeometry(QtCore.QRect(90, 10, 81, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.femaleradio.setFont(font)
        self.femaleradio.setStyleSheet("color: white;")
        self.femaleradio.setObjectName("femaleradio")
        self.label_6 = QtWidgets.QLabel(self.frame)
        self.label_6.setGeometry(QtCore.QRect(20, 230, 61, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_6.setObjectName("label_6")
        self.age_val = QtWidgets.QSpinBox(self.frame)
        self.age_val.setGeometry(QtCore.QRect(140, 240, 191, 22))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.age_val.setFont(font)
        self.age_val.setMinimum(3)
        self.age_val.setMaximum(20)
        self.age_val.setObjectName("age_val")
        self.label_8 = QtWidgets.QLabel(self.frame)
        self.label_8.setGeometry(QtCore.QRect(20, 280, 111, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(20)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet("QLabel{\n"
"    border: 2px white;\n"
"\n"
"}")
        self.label_8.setObjectName("label_8")
        self.txtrollno = QtWidgets.QLineEdit(self.frame)
        self.txtrollno.setGeometry(QtCore.QRect(140, 20, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.txtrollno.setFont(font)
        self.txtrollno.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}")
        self.txtrollno.setObjectName("txtrollno")
        self.txtname = QtWidgets.QLineEdit(self.frame)
        self.txtname.setGeometry(QtCore.QRect(140, 60, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.txtname.setFont(font)
        self.txtname.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}")
        self.txtname.setObjectName("txtname")
        self.txtphone = QtWidgets.QLineEdit(self.frame)
        self.txtphone.setGeometry(QtCore.QRect(140, 100, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.txtphone.setFont(font)
        self.txtphone.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}")
        self.txtphone.setObjectName("txtphone")
        self.txtemail = QtWidgets.QLineEdit(self.frame)
        self.txtemail.setGeometry(QtCore.QRect(140, 280, 181, 31))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        self.txtemail.setFont(font)
        self.txtemail.setStyleSheet("QLineEdit {\n"
"    border: 2px solid gray;\n"
"    border-radius: 10px;\n"
"    padding: 0 8px;\n"
"    background: white;\n"
"    selection-background-color: darkgray;\n"
"}")
        self.txtemail.setObjectName("txtemail")
        self.division = QtWidgets.QComboBox(self.frame)
        self.division.setGeometry(QtCore.QRect(230, 190, 91, 41))
        self.division.setObjectName("division")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.division.addItem("")
        self.grade = QtWidgets.QComboBox(self.frame)
        self.grade.setGeometry(QtCore.QRect(140, 189, 91, 41))
        self.grade.setObjectName("grade")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.grade.addItem("")
        self.label_7 = QtWidgets.QLabel(admission)
        self.label_7.setGeometry(QtCore.QRect(260, 40, 431, 91))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.table_adm = QtWidgets.QTableWidget(admission)
        self.table_adm.setGeometry(QtCore.QRect(380, 180, 591, 331))
        self.table_adm.setStyleSheet("COLOR: WHITE;\n"
"border: 1px solid white;")
        self.table_adm.setObjectName("table_adm")
        self.table_adm.setColumnCount(6)
        self.table_adm.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.table_adm.setHorizontalHeaderItem(5, item)
        self.label_9 = QtWidgets.QLabel(admission)
        self.label_9.setGeometry(QtCore.QRect(60, 170, 161, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(18)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet("COLOR: WHITE;\n"
"")
        self.label_9.setObjectName("label_9")
        self.btDelete = QtWidgets.QToolButton(admission)
        self.btDelete.setGeometry(QtCore.QRect(190, 520, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btDelete.setFont(font)
        self.btDelete.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btDelete.setObjectName("btDelete")
        self.btnModify = QtWidgets.QToolButton(admission)
        self.btnModify.setGeometry(QtCore.QRect(271, 520, 91, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnModify.setFont(font)
        self.btnModify.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnModify.setObjectName("btnModify")
        self.btnAdd = QtWidgets.QToolButton(admission)
        self.btnAdd.setGeometry(QtCore.QRect(110, 520, 71, 20))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnAdd.setFont(font)
        self.btnAdd.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnAdd.setObjectName("btnAdd")
        self.btnShow = QtWidgets.QToolButton(admission)
        self.btnShow.setGeometry(QtCore.QRect(30, 520, 71, 21))
        font = QtGui.QFont()
        font.setFamily("Times New Roman")
        font.setPointSize(-1)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.btnShow.setFont(font)
        self.btnShow.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnShow.setObjectName("btnShow")
        self.toolButton = QtWidgets.QToolButton(admission)
        self.toolButton.setGeometry(QtCore.QRect(910, 520, 61, 22))
        self.toolButton.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.toolButton.setObjectName("toolButton")
        self.btnShowAll = QtWidgets.QToolButton(admission)
        self.btnShowAll.setGeometry(QtCore.QRect(820, 520, 71, 22))
        self.btnShowAll.setStyleSheet("QToolButton { \n"
"    background-color: #33ff39;\n"
"    border: 2px;\n"
"    border-radius: 8px;\n"
"    FONT: 12PX;\n"
"    COLOR: BLACK;\n"
"\n"
"                    \n"
" }\n"
"\n"
"QToolButton:pressed {\n"
"    background-color: qlineargradient(x1: 0, y1: 0, x2: 0, y2: 1,\n"
"                                      stop: 0 #dadbde, stop: 1 #f6f7fa);}")
        self.btnShowAll.setObjectName("btnShowAll")

        self.retranslateUi(admission)
        QtCore.QMetaObject.connectSlotsByName(admission)

    def retranslateUi(self, admission):
        _translate = QtCore.QCoreApplication.translate
        admission.setWindowTitle(_translate("admission", "Form"))
        self.label.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">ROLL NO:</span></p></body></html>"))
        self.label_2.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">SEX: </span></p></body></html>"))
        self.label_3.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">PHONE NO:</span></p></body></html>"))
        self.label_4.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">NAME: </span></p></body></html>"))
        self.label_5.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">CLASS :</span></p></body></html>"))
        self.maleradio.setText(_translate("admission", "MALE"))
        self.femaleradio.setText(_translate("admission", "FEMALE"))
        self.label_6.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">AGE :</span></p></body></html>"))
        self.label_8.setText(_translate("admission", "<html><head/><body><p><span style=\" color:#ffffff;\">EMAIL ID: </span></p></body></html>"))
        self.txtrollno.setPlaceholderText(_translate("admission", "ROLL NO"))
        self.txtname.setPlaceholderText(_translate("admission", "NAME"))
        self.txtphone.setText(_translate("admission", "+971"))
        self.txtphone.setPlaceholderText(_translate("admission", "PHONE NO"))
        self.txtemail.setPlaceholderText(_translate("admission", "EMAIL ID"))
        self.division.setItemText(0, _translate("admission", "A"))
        self.division.setItemText(1, _translate("admission", "B"))
        self.division.setItemText(2, _translate("admission", "C"))
        self.division.setItemText(3, _translate("admission", "D"))
        self.division.setItemText(4, _translate("admission", "E"))
        self.division.setItemText(5, _translate("admission", "F"))
        self.division.setItemText(6, _translate("admission", "G"))
        self.division.setItemText(7, _translate("admission", "H"))
        self.grade.setItemText(0, _translate("admission", "KG-1"))
        self.grade.setItemText(1, _translate("admission", "KG-2"))
        self.grade.setItemText(2, _translate("admission", "1"))
        self.grade.setItemText(3, _translate("admission", "2"))
        self.grade.setItemText(4, _translate("admission", "3"))
        self.grade.setItemText(5, _translate("admission", "4"))
        self.grade.setItemText(6, _translate("admission", "5"))
        self.grade.setItemText(7, _translate("admission", "6"))
        self.grade.setItemText(8, _translate("admission", "7"))
        self.grade.setItemText(9, _translate("admission", "8"))
        self.grade.setItemText(10, _translate("admission", "9"))
        self.grade.setItemText(11, _translate("admission", "10"))
        self.grade.setItemText(12, _translate("admission", "11"))
        self.grade.setItemText(13, _translate("admission", "12"))
        self.label_7.setText(_translate("admission", "<html><head/><body><p><span style=\" font-size:48pt; color:#ffffff;\">ADMISSION MENU</span></p></body></html>"))
        item = self.table_adm.horizontalHeaderItem(0)
        item.setText(_translate("admission", "ROLL NO"))
        item = self.table_adm.horizontalHeaderItem(1)
        item.setText(_translate("admission", "NAME"))
        item = self.table_adm.horizontalHeaderItem(2)
        item.setText(_translate("admission", "AGE"))
        item = self.table_adm.horizontalHeaderItem(3)
        item.setText(_translate("admission", "SEX"))
        item = self.table_adm.horizontalHeaderItem(4)
        item.setText(_translate("admission", "CLASS"))
        item = self.table_adm.horizontalHeaderItem(5)
        item.setText(_translate("admission", "EMAIL ID"))
        self.label_9.setText(_translate("admission", "STUDENT DETAILS"))
        self.btDelete.setText(_translate("admission", "DELETE"))
        self.btnModify.setText(_translate("admission", "MODIFY"))
        self.btnAdd.setText(_translate("admission", "ADD"))
        self.btnShow.setText(_translate("admission", "SHOW"))
        self.toolButton.setText(_translate("admission", "RETURN"))
        self.btnShowAll.setText(_translate("admission", "SHOW ALL"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    admission = QtWidgets.QWidget()
    ui = Ui_admission()
    ui.setupUi(admission)
    admission.show()
    sys.exit(app.exec_())
